name: notebook-diff-web-exporter

on:
  pull_request:
  workflow_dispatch:

jobs:
  diff-action-test:
    runs-on: ubuntu-latest
    name: diff notebooks
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Export notebooks diff
        uses: kuromt/diff-notebooks@v0.0.1
        id: nbdiff-web-exporter-action
        with:
          remote: "origin/diff-notebooks"
          export_dir: "./artifacts"

      - uses: actions/upload-artifact@v2
        with:
          name: diff-notebooks
          path: ${{steps.nbdiff-web-exporter-action.outputs.export_dir}}
